word = input("문장 입력: ")
print("###############")
print("대문자 변환:",word.upper())
print("소문자 변환:",word.lower())
print("문자열 길이:",len(word))
print("공백으로 분리:",word.split())
print("마침표로 분리:",word.split("."))
print("o의 위치:",word.index("o"))
print("o의 개수:",word.count("o"))
print("Python을 AI로 교체:",word.replace("Python","AI"))